In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.datasets import load_digits
digits=load_digits()

In [ ]:
type(digits)

sklearn.utils.Bunch

In [ ]:
X=digits.data
print(X)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [ ]:
X.shape

(1797, 64)

In [ ]:
X=pd.DataFrame(X)

In [ ]:
print(X)

       0    1     2     3     4     5   ...   58    59    60    61   62   63
0     0.0  0.0   5.0  13.0   9.0   1.0  ...  6.0  13.0  10.0   0.0  0.0  0.0
1     0.0  0.0   0.0  12.0  13.0   5.0  ...  0.0  11.0  16.0  10.0  0.0  0.0
2     0.0  0.0   0.0   4.0  15.0  12.0  ...  0.0   3.0  11.0  16.0  9.0  0.0
3     0.0  0.0   7.0  15.0  13.0   1.0  ...  7.0  13.0  13.0   9.0  0.0  0.0
4     0.0  0.0   0.0   1.0  11.0   0.0  ...  0.0   2.0  16.0   4.0  0.0  0.0
...   ...  ...   ...   ...   ...   ...  ...  ...   ...   ...   ...  ...  ...
1792  0.0  0.0   4.0  10.0  13.0   6.0  ...  2.0  14.0  15.0   9.0  0.0  0.0
1793  0.0  0.0   6.0  16.0  13.0  11.0  ...  6.0  16.0  14.0   6.0  0.0  0.0
1794  0.0  0.0   1.0  11.0  15.0   1.0  ...  2.0   9.0  13.0   6.0  0.0  0.0
1795  0.0  0.0   2.0  10.0   7.0   0.0  ...  5.0  12.0  16.0  12.0  0.0  0.0
1796  0.0  0.0  10.0  14.0   8.0   1.0  ...  8.0  12.0  14.0  12.0  1.0  0.0

[1797 rows x 64 columns]


In [ ]:
Y=digits.target
Y=pd.DataFrame(Y)
print(Y)

      0
0     0
1     1
2     2
3     3
4     4
...  ..
1792  9
1793  0
1794  8
1795  9
1796  8

[1797 rows x 1 columns]


In [ ]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_scaled=pd.DataFrame(ss.fit_transform(X))
print(X_scaled)

       0         1         2         3   ...        60        61        62        63
0     0.0 -0.335016 -0.043081  0.274072  ... -0.366771 -1.146647 -0.505670 -0.196008
1     0.0 -0.335016 -1.094937  0.038648  ...  0.849632  0.548561 -0.505670 -0.196008
2     0.0 -0.335016 -1.094937 -1.844742  ... -0.164037  1.565686  1.695137 -0.196008
3     0.0 -0.335016  0.377661  0.744919  ...  0.241430  0.379040 -0.505670 -0.196008
4     0.0 -0.335016 -1.094937 -2.551014  ...  0.849632 -0.468564 -0.505670 -0.196008
...   ...       ...       ...       ...  ...       ...       ...       ...       ...
1792  0.0 -0.335016 -0.253452 -0.432200  ...  0.646898  0.379040 -0.505670 -0.196008
1793  0.0 -0.335016  0.167290  0.980343  ...  0.444164 -0.129523 -0.505670 -0.196008
1794  0.0 -0.335016 -0.884566 -0.196776  ...  0.241430 -0.129523 -0.505670 -0.196008
1795  0.0 -0.335016 -0.674195 -0.432200  ...  0.849632  0.887602 -0.505670 -0.196008
1796  0.0 -0.335016  1.008775  0.509495  ...  0.444164  0.887602 

In [ ]:
Cov_matrix=X_scaled.cov()
print(Cov_matrix)

     0         1         2         3   ...        60        61        62        63
0   0.0  0.000000  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000
1   0.0  1.000557  0.556928  0.207929  ... -0.102406 -0.029887  0.026562 -0.043913
2   0.0  0.556928  1.000557  0.560492  ... -0.134829 -0.041206  0.072639  0.082569
3   0.0  0.207929  0.560492  1.000557  ... -0.065993 -0.054966  0.053467  0.082016
4   0.0 -0.018771 -0.084282  0.023952  ... -0.082171 -0.215929 -0.250838 -0.215469
..  ...       ...       ...       ...  ...       ...       ...       ...       ...
59  0.0  0.147728  0.500118  0.768373  ...  0.058423 -0.095009  0.006853  0.099727
60  0.0 -0.102406 -0.134829 -0.065993  ...  1.000557  0.609854  0.243441  0.103073
61  0.0 -0.029887 -0.041206 -0.054966  ...  0.609854  1.000557  0.648689  0.262137
62  0.0  0.026562  0.072639  0.053467  ...  0.243441  0.648689  1.000557  0.620774
63  0.0 -0.043913  0.082569  0.082016  ...  0.103073  0.262137  0.620774  1.000557

[64

In [ ]:
eigen_values, eig_vectors=np.linalg.eig(Cov_matrix)

In [ ]:
eigen_values

array([7.34477606, 5.83549054, 5.15396118, 3.96623597, 2.9663452 ,
       2.57204442, 2.40600941, 2.06867355, 1.82993314, 1.78951739,
       1.69784616, 1.57287889, 1.38870781, 1.35933609, 1.32152536,
       1.16829176, 1.08368678, 0.99977862, 0.97438293, 0.90891242,
       0.82271926, 0.77631014, 0.71155675, 0.64552365, 0.59527399,
       0.5765018 , 0.52673155, 0.5106363 , 0.48686381, 0.45560107,
       0.44285155, 0.42230086, 0.3991063 , 0.39110111, 0.36094517,
       0.34860306, 0.3195963 , 0.29406627, 0.05037444, 0.27692285,
       0.06328961, 0.258273  , 0.24783029, 0.2423566 , 0.07635394,
       0.08246812, 0.09018543, 0.09840876, 0.10250434, 0.11188655,
       0.11932898, 0.12426371, 0.13321081, 0.14311427, 0.217582  ,
       0.15818474, 0.16875236, 0.20799593, 0.17612894, 0.2000909 ,
       0.18983516, 0.        , 0.        , 0.        ])

In [ ]:
eig_pairs=[]
for i in range(len(eigen_values)):
  eig_pairs.append((eigen_values[i],eig_vectors[:,i]))

In [ ]:
eig_pairs

[(7.344776062836356,
  array([ 0.        ,  0.18223392,  0.285868  ,  0.22036967, -0.02516956,
         -0.00949725, -0.0524765 , -0.06269499,  0.03470727,  0.24553368,
          0.22915174, -0.10794381,  0.03620209,  0.03871159, -0.08378077,
         -0.09277502,  0.01669934,  0.1367165 , -0.06305075, -0.12287927,
          0.14819348, -0.02348425, -0.1711997 , -0.10420837, -0.00394882,
         -0.1163897 , -0.18820473,  0.0658604 ,  0.14353257, -0.12820705,
         -0.18062075, -0.05270917,  0.        , -0.23890251, -0.23500613,
         -0.00509137, -0.01310881, -0.15911618, -0.12939416,  0.        ,
         -0.05559906, -0.18715707, -0.15353371, -0.04682572, -0.11089272,
         -0.10720947,  0.01792652, -0.00227271, -0.02881729,  0.040868  ,
          0.11027068,  0.0318244 , -0.07904945,  0.06832147,  0.12124707,
          0.04877119, -0.00183586,  0.16039569,  0.27985301,  0.19444929,
          0.01777381,  0.103198  ,  0.1198106 ,  0.07149362])),
 (5.8354905373295285,
  arr

In [ ]:
def first_ele(tup):
  return tup[0]

sorted_eig_pairs=sorted(eig_pairs, reverse=True, key=first_ele)

In [ ]:
for i in sorted_eig_pairs:
  print(i[0])

7.344776062836356
5.8354905373295285
5.153961176418873
3.9662359665873037
2.9663451950935933
2.5720444193206173
2.406009413578209
2.0686735457465546
1.8299331438269713
1.7895173923196779
1.69784615533406
1.57287888687952
1.3887078149450487
1.3593360885653987
1.3215253598609054
1.1682917644675226
1.0836867752499009
0.9997786171449681
0.974382930568951
0.9089124184577178
0.822719264455819
0.7763101392595959
0.7115567531171418
0.6455236480610065
0.5952739876615556
0.5765017972018535
0.5267315516205446
0.510636301172504
0.48686381297937237
0.45560107052785287
0.4428515517079933
0.42230086300618414
0.39910630258276025
0.3911011111763697
0.3609451680104019
0.34860305887186704
0.31959630000067735
0.29406627062002927
0.2769228513803112
0.2582730040151321
0.24783028603503565
0.24235660038291532
0.2175819956045909
0.20799592689994376
0.20009090171636879
0.1898351645277068
0.1761289421733806
0.16875235857272133
0.15818474106126712
0.14311427404120178
0.13321081276067545
0.12426370770472378
0.1193

In [ ]:
result = pd.DataFrame()
#1st 40 features are selected 
for i in range(40):
    PC = X_scaled.dot(sorted_eig_pairs[i][1].T)
    result['PC'+str(i+1)] = PC
result['number'] = Y
result

PC1       PC2       PC3  ...      PC39      PC40  number
0    -1.914214  0.954502 -3.946035  ...  0.024931  0.321931       0
1    -0.588980 -0.924636  3.924755  ...  0.087108 -0.489143       1
2    -1.302039  0.317189  3.023333  ... -1.278875  0.545834       2
3     3.020770  0.868772 -0.801744  ...  0.772751 -0.050325       3
4    -4.528949  1.093480  0.973121  ... -0.133426  0.184994       4
...        ...       ...       ...  ...       ...       ...     ...
1792 -0.104331 -0.255024 -3.765861  ... -0.756333 -0.285562       9
1793 -2.423234  1.429611 -3.045245  ... -0.061084 -0.404112       0
1794 -1.022596  0.147911  2.469974  ...  0.412388  1.208864       8
1795 -1.076055  0.380906 -2.455487  ... -0.698635 -0.443400       9
1796  1.257702  2.227591  0.283628  ...  0.128551  1.321372       8

[1797 rows x 41 columns]